### ISSUE TITLE
Symlinking templates and SUPEE-9767v2 (composer install)

### ISSUE THREAD

**Issue by holozaen** [diglin/Diglin_Ricardo#6]
SUPEE-9767v2 has disabled and removed the option in "Advanced -> Developer -> Template settings", that would allow us to enable/disable symlinks. 

The Magento part of Diglin Ricardo (Ricento) uses symlinking for its templates. This leads to a nonfunctional dashboard and some notices in the logs (Not valid template file).

As far as I see there are two workarounds at the moment.

1. Enabling symlinking via config table (see https://magento.stackexchange.com/questions/184184/how-to-enable-symlinks-after-supee-9767-v2-install). Maybe unsecure??

2. Copy the templates by hand (bad...)

**Comment by diglin** [comment]
Hi,

There is no symlink done by the module itself. It depends how do you install the module with modman or via composer.

With modman you have the parameter `--copy` when you run `modman clone --copy https://github.com/diglin/ricento.git`, it will copy all the files instead of symlink them. 

With composer, you need to add ` "magento-deploystrategy": "link"` (or `copy`) under the section `extra` in the composer.json in root of your project. Unlike the name `link` means here it's doing a `hard symlink` not a `symlink` which is ok with Magento.
